### ISSUE TITLE
Broken Image when using `<`

### ISSUE THREAD

**Issue by donno2048** [AndrewSink/STL-to-ASCII-Generator#1]
Try using `<a` in the custom ASCII field

**Comment by AndrewSink** [comment]
Good catch! Not sure what's going on here; I'll take a look and see what I can find.

**Comment by GeekDad63** [comment]
Also happens with <A> or any letter in between the <>. I don't know enough about code (only enough to get me in trouble) but the<> might be telling the generator something it doesn't like.

**Comment by AndrewSink** [comment]
Huh. Yeah, definitely worth investigating a little further. I'm still not sure what's causing this issue, but I'll try diving a little deeper this weekend. Thanks for the heads-up!

**Comment by donno2048** [comment]
I guess your weekend is over... Closing as stale
