### ISSUE TITLE
white-space and line breaks when copying to clipboard misbehave

### ISSUE THREAD

**Issue by klsrqm** [AndrewSink/STL-to-ASCII-Generator#10]
when I click "copy to clibpoard", the resulting string has some very strange linebreaks. 

pasting into VSCode gives all sorts of errors.

Please see screenshot attached.

Pasting into TextEdit seems to produce better results.

The resulting string is also affected by the same bug as in [/issues/9] - only half the image is copied to clipboard.
![CleanShot 2024-04-08 at 11 32 35](https://github.com/AndrewSink/STL-to-ASCII-Generator/assets/31819201/3729a7eb-5186-4a16-b537-04ab1f7669ea)
![CleanShot 2024-04-08 at 11 33 15](https://github.com/AndrewSink/STL-to-ASCII-Generator/assets/31819201/0b6b40d7-e8df-4c7d-a203-1e23e3451dc1)

**Comment by AndrewSink** [comment]
That issue was resolved by changing the size of the text viewer. Can you try resizing your window and see if that fixes the visualization?

**Comment by klsrqm** [comment]
I think this really is a duplicate of the other issue. Thanks for looking into my stupid oversight.
