### ISSUE TITLE
text file download creates only half the model

### ISSUE THREAD

**Issue by klsrqm** [AndrewSink/STL-to-ASCII-Generator#9]
When I click "Download text file" the output only has half the model in it, it is vertically split in the middle. Tested using Safari and Firefox. Attaching some sample output.

[ASCII-1.txt](https://github.com/AndrewSink/STL-to-ASCII-Generator/files/14904289/ASCII-1.txt)

**Comment by AndrewSink** [comment]
This is what I see when I open this text, does this look correct to you? 

I had to resize the window to fit the entire image, maybe give that a shot? 

<img width="687" alt="image" src="https://github.com/AndrewSink/STL-to-ASCII-Generator/assets/46334898/99de63aa-bad0-4e03-a77c-294ec91e8481">

**Comment by klsrqm** [comment]
🤦 That really is all there was to it, I'm sorry for not having noticed it! Duh! Thanks for getting back to me about it.

**Comment by AndrewSink** [comment]
Marking as closed!
